### ISSUE TITLE
Feed毎にSlack表示名と絵文字を変更できるように

### ISSUE THREAD

**Issue by ryosan-470** [ryosan-470/rssnotify#16]
変えられるようにできるならしたいという願望。

```yaml
notifier:
  slack:
     token: "~~~"
     channel: "~~~"
     icon: ":emoji:"  // 絵文字かLink?
     name: "rss"

feed:
   - url: https://example.com/feed1.xml
      icon: ":sob:"
      name: "example1"
   - url: https://example.com/feed2.xml
```

こんな感じにする。feed1.xml のときはSlackでは、アイコンと表示名が :sob: で example1 となり、設定されていないときはデフォルト値を踏襲する。
